### ISSUE TITLE
Cannot read file tsconfig.json

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/Network-of-Terms-Workshop#1]
While following the instructions https://github.com/netwerk-digitaal-erfgoed/network-of-terms-tutorial/wiki/Running-the-GraphQL-API I get an error on the `npm run dev` command (on a Windows machine):
```
16:01:14 - Starting compilation in watch mode...

error TS5083: Cannot read file 'C:/workshop/network-of-terms-tutorial/network-of-terms/packages/network-of-terms-graphql/run/tsconfig.json'.
error TS5083: Cannot read file 'C:/workshop/network-of-terms-tutorial/network-of-terms/packages/network-of-terms-graphql/start'/tsconfig.json'.

16:01:14 - Found 2 errors. Watching for file changes.
[..................] \ : timing config:load:flatten Completed in 2ms
```
There's no tsconfig.json file within the network-of-terms/packages/network-of-terms-graphql directory.
As a result, the GraphQL API is not available via http://localhost:3123/.

**Comment by rschalkrce** [comment]
I have the same issue (also Windows machine). Local Docker dev does work, btw.

**Comment by coret** [comment]
FYI, I'm running node v18.12.1 and npm v8.19.2

**Comment by coret** [comment]
Same error, when running `npm run dev` on the reconciliation package (as described on https://github.com/netwerk-digitaal-erfgoed/network-of-terms-tutorial/wiki/Running-the-Reconciliation-API)

**Comment by ddeboer** [comment]
> There's no tsconfig.json file within the network-of-terms/packages/network-of-terms-graphql directory.

There doesn’t need to be, because `tsconfig.json.build` is used instead. No idea why Node on Windows is looking for `tsconfig.json` in two imagined (non-existing) directories `network-of-terms-graphql/run` and `start'`. I have no easy way to run this on Windows.

For Windows machines, would the Docker workflow be a good workaround?

**Comment by coret** [comment]
Observation: running `npm run start` does work as expected.

When I change the following line in `package.json`:
```
"start": "node --experimental-specifier-resolution=node build/main.js",
"dev": "tsc-watch --build tsconfig.build.json --onSuccess 'npm run start'",
```
into
```
"start": "node --experimental-specifier-resolution=node build/main.js",
"dev": "tsc-watch --build tsconfig.build.json --onSuccess \"node --experimental-specifier-resolution=node build/main.js\"",
```
I do get the "Server listening..." message when running `npm run dev`!!

Note 1: `--onSuccess 'node ..'` doesn't work on Windows (so in the change no single quotes but escaped double quotes), but does work on *nix
Note 2: change tested on Windows and Unix, both working.

@ddeboer is this a change (to https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/6627da7dd020163fb45b25cf07ce3f3cc614b639/packages/network-of-terms-reconciliation/package.json#L39 and https://github.com/netwerk-digitaal-erfgoed/network-of-terms/blob/6627da7dd020163fb45b25cf07ce3f3cc614b639/packages/network-of-terms-graphql/package.json#L33) acceptable?

**Comment by coret** [comment]
Ah, 'Note 1' actually described the real problem!

So the proposed change is even easier (and tested on Windows and *nix):
```
"dev": "tsc-watch --build tsconfig.build.json --onSuccess 'npm run start'",
```
should be
```
"dev": "tsc-watch --build tsconfig.build.json --onSuccess \"npm run start\"",
```

**Comment by EnnoMeijers** [comment]
Nice work @coret, I suggest to create a PR for with this fix and add the changed package,json in the root of the Tutorial repo for the mean time.

**Comment by ddeboer** [comment]
@coret The change looks fine but as @EnnoMeijers says, please submit it as a PR.

**Comment by EnnoMeijers** [comment]
just created a PR on the main repo, see https://github.com/netwerk-digitaal-erfgoed/network-of-terms/pull/1097/commits/c8626afe0558acfdb91e57983a25ec387ccecdfb

**Comment by ddeboer** [comment]
And merged, so I’m assuming this can be closed.
